import path from 'node:path';
import type { ThemeName, TokenType, TypographyValue } from './types.ts';

export const ROOT_DIR = process.cwd();
export const OUT_DIR = path.join(ROOT_DIR, 'dist');
export const THEMES: ThemeName[] = ['light', 'dark'];
export const PREFIX = 'rds';
export const HEADER = '/* Generated by scripts/build-tokens.ts. Do not edit directly. */';

export const GENERIC_FONT_FAMILIES = new Set([
  'serif',
  'sans-serif',
  'monospace',
  'cursive',
  'fantasy',
  'system-ui',
  'ui-serif',
  'ui-sans-serif',
  'ui-monospace',
  'ui-rounded',
]);

export const TYPOGRAPHY_PART_TYPES: Record<keyof TypographyValue, TokenType> = {
  fontFamily: 'fontFamily',
  fontSize: 'dimension',
  fontWeight: 'fontWeight',
  lineHeight: 'number',
  letterSpacing: 'dimension',
};

export const themeSelector: Record<ThemeName, string> = {
  light: ':root',
  dark: "[data-theme='dark']",
};

export const tokenIncludes = (): string[] => [
  'tokens/primitive/**/*.tokens.json',
  'tokens/semantic/**/*.tokens.json',
];

export const tokenSources = (theme: ThemeName): string[] => [
  `tokens/theme/${theme}/**/*.tokens.json`,
];
