name: Check
description: Run lint, build and test

runs:
  using: 'composite'
  steps:
    - name: Lint packages
      run: bun run --filter '*' lint
      shell: bash

    - name: Build packages
      run: bun run --filter '*' build
      shell: bash

    - name: Run tests
      run: bun run --filter '*' test
      shell: bash
