export const ModifierKeyCodes = {
  ControlLeft: 'ControlLeft',
  ControlRight: 'ControlRight',
  ShiftLeft: 'ShiftLeft',
  ShiftRight: 'ShiftRight',
  AltLeft: 'AltLeft',
  AltRight: 'AltRight',
  MetaLeft: 'MetaLeft',
  MetaRight: 'MetaRight',
  // firefox only
  OSLeft: 'OSLeft',
  OSRight: 'OSRight',
} as const;

export type ModifierKeyCode =
  (typeof ModifierKeyCodes)[keyof typeof ModifierKeyCodes];

export const NormalKeyCodes = {
  // functions keys
  F1: 'F1',
  F2: 'F2',
  F3: 'F3',
  F4: 'F4',
  F5: 'F5',
  F6: 'F6',
  F7: 'F7',
  F8: 'F8',
  F9: 'F9',
  F10: 'F10',
  F11: 'F11',
  F12: 'F12',
  // numbers keys
  Digit1: 'Digit1',
  Digit2: 'Digit2',
  Digit3: 'Digit3',
  Digit4: 'Digit4',
  Digit5: 'Digit5',
  Digit6: 'Digit6',
  Digit7: 'Digit7',
  Digit8: 'Digit8',
  Digit9: 'Digit9',
  Digit0: 'Digit0',
  // numpad keys
  Numpad1: 'Numpad1',
  Numpad2: 'Numpad2',
  Numpad3: 'Numpad3',
  Numpad4: 'Numpad4',
  Numpad5: 'Numpad5',
  Numpad6: 'Numpad6',
  Numpad7: 'Numpad7',
  Numpad8: 'Numpad8',
  Numpad9: 'Numpad9',
  Numpad0: 'Numpad0',
  NumpadEnter: 'NumpadEnter',
  NumpadMultiply: 'NumpadMultiply',
  NumpadDivide: 'NumpadDivide',
  NumpadSubtract: 'NumpadSubtract',
  NumpadAdd: 'NumpadAdd',
  NumLock: 'NumLock',
  NumpadDecimal: 'NumpadDecimal',
  // words
  KeyA: 'KeyA',
  KeyB: 'KeyB',
  KeyC: 'KeyC',
  KeyD: 'KeyD',
  KeyE: 'KeyE',
  KeyF: 'KeyF',
  KeyG: 'KeyG',
  KeyH: 'KeyH',
  KeyI: 'KeyI',
  KeyJ: 'KeyJ',
  KeyK: 'KeyK',
  KeyL: 'KeyL',
  KeyM: 'KeyM',
  KeyN: 'KeyN',
  KeyO: 'KeyO',
  KeyP: 'KeyP',
  KeyQ: 'KeyQ',
  KeyR: 'KeyR',
  KeyS: 'KeyS',
  KeyT: 'KeyT',
  KeyU: 'KeyU',
  KeyV: 'KeyV',
  KeyW: 'KeyW',
  KeyX: 'KeyX',
  KeyY: 'KeyY',
  KeyZ: 'KeyZ',
  // punctuations
  Comma: 'Comma',
  Period: 'Period',
  Slash: 'Slash',
  Semicolon: 'Semicolon',
  Quote: 'Quote',
  BracketLeft: 'BracketLeft',
  BracketRight: 'BracketRight',
  Backslash: 'Backslash',
  Backquote: 'Backquote',
  // others
  Space: 'Space',
  Escape: 'Escape',
  Minus: 'Minus',
  Equal: 'Equal',
  Backspace: 'Backspace',
  Delete: 'Delete',
  Tab: 'Tab',
  CapsLock: 'CapsLock',
  Enter: 'Enter',
  ArrowUp: 'ArrowUp',
  ArrowDown: 'ArrowDown',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  Home: 'Home',
  End: 'End',
  PageUp: 'PageUp',
  PageDown: 'PageDown',
  Insert: 'Insert',
} as const;

export type NormalKeyCode = keyof typeof NormalKeyCodes;

export type KeyCode = ModifierKeyCode | NormalKeyCode;

export const ModifierKeyCodeNames = {
  Ctrl: 'Ctrl',
  CtrlLeft: 'CtrlLeft',
  CtrlRight: 'CtrlRight',
  Control: 'Control',
  ControlLeft: 'ControlLeft',
  ControlRight: 'ControlRight',
  Shift: 'Shift',
  ShiftLeft: 'ShiftLeft',
  ShiftRight: 'ShiftRight',
  // MacOS
  Option: 'Option',
  OptionLeft: 'OptionLeft',
  OptionRight: 'OptionRight',
  // Others
  Alt: 'Alt',
  AltLeft: 'AltLeft',
  AltRight: 'AltRight',
  // Universal
  Meta: 'Meta',
  MetaLeft: 'MetaLeft',
  MetaRight: 'MetaRight',
  Super: 'Super',
  SuperLeft: 'SuperLeft',
  SuperRight: 'SuperRight',
  // MacOS
  Command: 'Command',
  CommandLeft: 'CommandLeft',
  CommandRight: 'CommandRight',
  Cmd: 'Cmd',
  CmdLeft: 'CmdLeft',
  CmdRight: 'CmdRight',
  // Windows
  Win: 'Win',
  WinLeft: 'WinLeft',
  WinRight: 'WinRight',
} as const;

export type ModifierKeyCodeName =
  (typeof ModifierKeyCodeNames)[keyof typeof ModifierKeyCodeNames];

export const NormalKeyCodeNames = {
  // functions keys
  F1: 'F1',
  F2: 'F2',
  F3: 'F3',
  F4: 'F4',
  F5: 'F5',
  F6: 'F6',
  F7: 'F7',
  F8: 'F8',
  F9: 'F9',
  F10: 'F10',
  F11: 'F11',
  F12: 'F12',
  // numbers keys
  One: '1',
  Two: '2',
  Three: '3',
  Four: '4',
  Five: '5',
  Six: '6',
  Seven: '7',
  Eight: '8',
  Nine: '9',
  Zero: '0',
  Minus: '-',
  Equal: '=',
  Plus: '+',
  Multiply: '*',
  // numpad keys
  NumpadOne: 'num1',
  NumpadTwo: 'num2',
  NumpadThree: 'num3',
  NumpadFour: 'num4',
  NumpadFive: 'num5',
  NumpadSix: 'num6',
  NumpadSeven: 'num7',
  NumpadEight: 'num8',
  NumpadNine: 'num9',
  NumpadZero: 'num0',
  NumpadEnter: 'numenter',
  NumpadMultiply: 'nummult',
  NumpadDivide: 'numdiv',
  NumpadSubtract: 'numsub',
  NumpadAdd: 'numadd',
  NumLock: 'numLock',
  NumpadDecimal: 'numdec',
  // words
  A: 'A',
  B: 'B',
  C: 'C',
  D: 'D',
  E: 'E',
  F: 'F',
  G: 'G',
  H: 'H',
  I: 'I',
  J: 'J',
  K: 'K',
  L: 'L',
  M: 'M',
  N: 'N',
  O: 'O',
  P: 'P',
  Q: 'Q',
  R: 'R',
  S: 'S',
  T: 'T',
  U: 'U',
  V: 'V',
  W: 'W',
  X: 'X',
  Y: 'Y',
  Z: 'Z',
  a: 'a',
  b: 'b',
  c: 'c',
  d: 'd',
  e: 'e',
  f: 'f',
  g: 'g',
  h: 'h',
  i: 'i',
  j: 'j',
  k: 'k',
  l: 'l',
  m: 'm',
  n: 'n',
  o: 'o',
  p: 'p',
  q: 'q',
  r: 'r',
  s: 's',
  t: 't',
  u: 'u',
  v: 'v',
  w: 'w',
  x: 'x',
  y: 'y',
  z: 'z',
  // punctuations
  Comma: ',',
  Period: '.',
  Slash: '/',
  Semicolon: ';',
  // eslint-disable-next-line quotes
  Quote: "'",
  BracketLeft: '[',
  BracketRight: ']',
  Backslash: '\\',
  Backquote: '`',
  // others
  Space: 'Space',
  Esc: 'Esc',
  Escape: 'Escape',
  Backspace: 'Backspace',
  Delete: 'Delete',
  Tab: 'Tab',
  CapsLock: 'CapsLock',
  Enter: 'Enter',
  ArrowUp: 'ArrowUp',
  ArrowDown: 'ArrowDown',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  Home: 'Home',
  End: 'End',
  PageUp: 'PageUp',
  PageDown: 'PageDown',
  Insert: 'Insert',
} as const;

export type NormalKeyCodeName =
  (typeof NormalKeyCodeNames)[keyof typeof NormalKeyCodeNames];

export type KeyCodeName = ModifierKeyCodeName | NormalKeyCodeName;

export const keyCodeName2KeyCode: Record<KeyCodeName, KeyCode[]> = {
  // modifiers
  [ModifierKeyCodeNames.Ctrl]: [
    ModifierKeyCodes.ControlLeft,
    ModifierKeyCodes.ControlRight,
  ],
  [ModifierKeyCodeNames.CtrlLeft]: [ModifierKeyCodes.ControlLeft],
  [ModifierKeyCodeNames.CtrlRight]: [ModifierKeyCodes.ControlRight],
  [ModifierKeyCodeNames.Control]: [
    ModifierKeyCodes.ControlLeft,
    ModifierKeyCodes.ControlRight,
  ],
  [ModifierKeyCodeNames.ControlLeft]: [ModifierKeyCodes.ControlLeft],
  [ModifierKeyCodeNames.ControlRight]: [ModifierKeyCodes.ControlRight],
  [ModifierKeyCodeNames.Shift]: [
    ModifierKeyCodes.ShiftLeft,
    ModifierKeyCodes.ShiftRight,
  ],
  [ModifierKeyCodeNames.ShiftLeft]: [ModifierKeyCodes.ShiftLeft],
  [ModifierKeyCodeNames.ShiftRight]: [ModifierKeyCodes.ShiftRight],
  [ModifierKeyCodeNames.Option]: [
    ModifierKeyCodes.AltLeft,
    ModifierKeyCodes.AltRight,
  ],
  [ModifierKeyCodeNames.OptionLeft]: [ModifierKeyCodes.AltLeft],
  [ModifierKeyCodeNames.OptionRight]: [ModifierKeyCodes.AltRight],
  [ModifierKeyCodeNames.Meta]: [
    ModifierKeyCodes.MetaLeft,
    ModifierKeyCodes.MetaRight,
    ModifierKeyCodes.OSLeft,
    ModifierKeyCodes.OSRight,
  ],
  [ModifierKeyCodeNames.Alt]: [
    ModifierKeyCodes.AltLeft,
    ModifierKeyCodes.AltRight,
  ],
  [ModifierKeyCodeNames.AltLeft]: [ModifierKeyCodes.AltLeft],
  [ModifierKeyCodeNames.AltRight]: [ModifierKeyCodes.AltRight],
  [ModifierKeyCodeNames.MetaLeft]: [
    ModifierKeyCodes.MetaLeft,
    ModifierKeyCodes.OSLeft,
  ],
  [ModifierKeyCodeNames.MetaRight]: [
    ModifierKeyCodes.MetaRight,
    ModifierKeyCodes.OSRight,
  ],
  [ModifierKeyCodeNames.Super]: [
    ModifierKeyCodes.MetaLeft,
    ModifierKeyCodes.MetaRight,
    ModifierKeyCodes.OSLeft,
    ModifierKeyCodes.OSRight,
  ],
  [ModifierKeyCodeNames.SuperLeft]: [
    ModifierKeyCodes.MetaLeft,
    ModifierKeyCodes.OSLeft,
  ],
  [ModifierKeyCodeNames.SuperRight]: [
    ModifierKeyCodes.MetaRight,
    ModifierKeyCodes.OSRight,
  ],
  [ModifierKeyCodeNames.Command]: [
    ModifierKeyCodes.MetaLeft,
    ModifierKeyCodes.MetaRight,
    ModifierKeyCodes.OSLeft,
    ModifierKeyCodes.OSRight,
  ],
  [ModifierKeyCodeNames.CommandLeft]: [
    ModifierKeyCodes.MetaLeft,
    ModifierKeyCodes.OSLeft,
  ],
  [ModifierKeyCodeNames.CommandRight]: [
    ModifierKeyCodes.MetaRight,
    ModifierKeyCodes.OSRight,
  ],
  [ModifierKeyCodeNames.Cmd]: [
    ModifierKeyCodes.MetaLeft,
    ModifierKeyCodes.MetaRight,
    ModifierKeyCodes.OSLeft,
    ModifierKeyCodes.OSRight,
  ],
  [ModifierKeyCodeNames.CmdLeft]: [
    ModifierKeyCodes.MetaLeft,
    ModifierKeyCodes.OSLeft,
  ],
  [ModifierKeyCodeNames.CmdRight]: [
    ModifierKeyCodes.MetaRight,
    ModifierKeyCodes.OSRight,
  ],
  [ModifierKeyCodeNames.Win]: [
    ModifierKeyCodes.MetaLeft,
    ModifierKeyCodes.MetaRight,
    ModifierKeyCodes.OSLeft,
    ModifierKeyCodes.OSRight,
  ],
  [ModifierKeyCodeNames.WinLeft]: [
    ModifierKeyCodes.MetaLeft,
    ModifierKeyCodes.OSLeft,
  ],
  [ModifierKeyCodeNames.WinRight]: [
    ModifierKeyCodes.MetaRight,
    ModifierKeyCodes.OSRight,
  ],
  // functions
  [NormalKeyCodeNames.F1]: [NormalKeyCodes.F1],
  [NormalKeyCodeNames.F2]: [NormalKeyCodes.F2],
  [NormalKeyCodeNames.F3]: [NormalKeyCodes.F3],
  [NormalKeyCodeNames.F4]: [NormalKeyCodes.F4],
  [NormalKeyCodeNames.F5]: [NormalKeyCodes.F5],
  [NormalKeyCodeNames.F6]: [NormalKeyCodes.F6],
  [NormalKeyCodeNames.F7]: [NormalKeyCodes.F7],
  [NormalKeyCodeNames.F8]: [NormalKeyCodes.F8],
  [NormalKeyCodeNames.F9]: [NormalKeyCodes.F9],
  [NormalKeyCodeNames.F10]: [NormalKeyCodes.F10],
  [NormalKeyCodeNames.F11]: [NormalKeyCodes.F11],
  [NormalKeyCodeNames.F12]: [NormalKeyCodes.F12],
  // numbers
  [NormalKeyCodeNames.One]: [NormalKeyCodes.Digit1, NormalKeyCodes.Numpad1],
  [NormalKeyCodeNames.Two]: [NormalKeyCodes.Digit2, NormalKeyCodes.Numpad2],
  [NormalKeyCodeNames.Three]: [NormalKeyCodes.Digit3, NormalKeyCodes.Numpad3],
  [NormalKeyCodeNames.Four]: [NormalKeyCodes.Digit4, NormalKeyCodes.Numpad4],
  [NormalKeyCodeNames.Five]: [NormalKeyCodes.Digit5, NormalKeyCodes.Numpad5],
  [NormalKeyCodeNames.Six]: [NormalKeyCodes.Digit6, NormalKeyCodes.Numpad6],
  [NormalKeyCodeNames.Seven]: [NormalKeyCodes.Digit7, NormalKeyCodes.Numpad7],
  [NormalKeyCodeNames.Eight]: [NormalKeyCodes.Digit8, NormalKeyCodes.Numpad8],
  [NormalKeyCodeNames.Nine]: [NormalKeyCodes.Digit9, NormalKeyCodes.Numpad9],
  [NormalKeyCodeNames.Zero]: [NormalKeyCodes.Digit0, NormalKeyCodes.Numpad0],
  [NormalKeyCodeNames.Minus]: [
    NormalKeyCodes.Minus,
    NormalKeyCodes.NumpadSubtract,
  ],
  [NormalKeyCodeNames.Equal]: [NormalKeyCodes.Equal],
  // numpad
  [NormalKeyCodeNames.NumpadOne]: [NormalKeyCodes.Numpad1],
  [NormalKeyCodeNames.NumpadTwo]: [NormalKeyCodes.Numpad2],
  [NormalKeyCodeNames.NumpadThree]: [NormalKeyCodes.Numpad3],
  [NormalKeyCodeNames.NumpadFour]: [NormalKeyCodes.Numpad4],
  [NormalKeyCodeNames.NumpadFive]: [NormalKeyCodes.Numpad5],
  [NormalKeyCodeNames.NumpadSix]: [NormalKeyCodes.Numpad6],
  [NormalKeyCodeNames.NumpadSeven]: [NormalKeyCodes.Numpad7],
  [NormalKeyCodeNames.NumpadEight]: [NormalKeyCodes.Numpad8],
  [NormalKeyCodeNames.NumpadNine]: [NormalKeyCodes.Numpad9],
  [NormalKeyCodeNames.NumpadZero]: [NormalKeyCodes.Numpad0],
  [NormalKeyCodeNames.NumpadEnter]: [NormalKeyCodes.NumpadEnter],
  [NormalKeyCodeNames.NumpadDivide]: [NormalKeyCodes.NumpadDivide],
  [NormalKeyCodeNames.NumpadMultiply]: [NormalKeyCodes.NumpadMultiply],
  [NormalKeyCodeNames.Multiply]: [NormalKeyCodes.NumpadMultiply],
  [NormalKeyCodeNames.NumpadSubtract]: [NormalKeyCodes.NumpadSubtract],
  [NormalKeyCodeNames.NumpadAdd]: [NormalKeyCodes.NumpadAdd],
  [NormalKeyCodeNames.Plus]: [NormalKeyCodes.NumpadAdd],
  [NormalKeyCodeNames.NumpadDecimal]: [NormalKeyCodes.NumpadDecimal],
  [NormalKeyCodeNames.NumLock]: [NormalKeyCodes.NumLock],
  // words
  [NormalKeyCodeNames.A]: [NormalKeyCodes.KeyA],
  [NormalKeyCodeNames.B]: [NormalKeyCodes.KeyB],
  [NormalKeyCodeNames.C]: [NormalKeyCodes.KeyC],
  [NormalKeyCodeNames.D]: [NormalKeyCodes.KeyD],
  [NormalKeyCodeNames.E]: [NormalKeyCodes.KeyE],
  [NormalKeyCodeNames.F]: [NormalKeyCodes.KeyF],
  [NormalKeyCodeNames.G]: [NormalKeyCodes.KeyG],
  [NormalKeyCodeNames.H]: [NormalKeyCodes.KeyH],
  [NormalKeyCodeNames.I]: [NormalKeyCodes.KeyI],
  [NormalKeyCodeNames.J]: [NormalKeyCodes.KeyJ],
  [NormalKeyCodeNames.K]: [NormalKeyCodes.KeyK],
  [NormalKeyCodeNames.L]: [NormalKeyCodes.KeyL],
  [NormalKeyCodeNames.M]: [NormalKeyCodes.KeyM],
  [NormalKeyCodeNames.N]: [NormalKeyCodes.KeyN],
  [NormalKeyCodeNames.O]: [NormalKeyCodes.KeyO],
  [NormalKeyCodeNames.P]: [NormalKeyCodes.KeyP],
  [NormalKeyCodeNames.Q]: [NormalKeyCodes.KeyQ],
  [NormalKeyCodeNames.R]: [NormalKeyCodes.KeyR],
  [NormalKeyCodeNames.S]: [NormalKeyCodes.KeyS],
  [NormalKeyCodeNames.T]: [NormalKeyCodes.KeyT],
  [NormalKeyCodeNames.U]: [NormalKeyCodes.KeyU],
  [NormalKeyCodeNames.V]: [NormalKeyCodes.KeyV],
  [NormalKeyCodeNames.W]: [NormalKeyCodes.KeyW],
  [NormalKeyCodeNames.X]: [NormalKeyCodes.KeyX],
  [NormalKeyCodeNames.Y]: [NormalKeyCodes.KeyY],
  [NormalKeyCodeNames.Z]: [NormalKeyCodes.KeyZ],
  [NormalKeyCodeNames.a]: [NormalKeyCodes.KeyA],
  [NormalKeyCodeNames.b]: [NormalKeyCodes.KeyB],
  [NormalKeyCodeNames.c]: [NormalKeyCodes.KeyC],
  [NormalKeyCodeNames.d]: [NormalKeyCodes.KeyD],
  [NormalKeyCodeNames.e]: [NormalKeyCodes.KeyE],
  [NormalKeyCodeNames.f]: [NormalKeyCodes.KeyF],
  [NormalKeyCodeNames.g]: [NormalKeyCodes.KeyG],
  [NormalKeyCodeNames.h]: [NormalKeyCodes.KeyH],
  [NormalKeyCodeNames.i]: [NormalKeyCodes.KeyI],
  [NormalKeyCodeNames.j]: [NormalKeyCodes.KeyJ],
  [NormalKeyCodeNames.k]: [NormalKeyCodes.KeyK],
  [NormalKeyCodeNames.l]: [NormalKeyCodes.KeyL],
  [NormalKeyCodeNames.m]: [NormalKeyCodes.KeyM],
  [NormalKeyCodeNames.n]: [NormalKeyCodes.KeyN],
  [NormalKeyCodeNames.o]: [NormalKeyCodes.KeyO],
  [NormalKeyCodeNames.p]: [NormalKeyCodes.KeyP],
  [NormalKeyCodeNames.q]: [NormalKeyCodes.KeyQ],
  [NormalKeyCodeNames.r]: [NormalKeyCodes.KeyR],
  [NormalKeyCodeNames.s]: [NormalKeyCodes.KeyS],
  [NormalKeyCodeNames.t]: [NormalKeyCodes.KeyT],
  [NormalKeyCodeNames.u]: [NormalKeyCodes.KeyU],
  [NormalKeyCodeNames.v]: [NormalKeyCodes.KeyV],
  [NormalKeyCodeNames.w]: [NormalKeyCodes.KeyW],
  [NormalKeyCodeNames.x]: [NormalKeyCodes.KeyX],
  [NormalKeyCodeNames.y]: [NormalKeyCodes.KeyY],
  [NormalKeyCodeNames.z]: [NormalKeyCodes.KeyZ],
  // punctuations
  [NormalKeyCodeNames.Comma]: [NormalKeyCodes.Comma],
  [NormalKeyCodeNames.Period]: [
    NormalKeyCodes.Period,
    NormalKeyCodes.NumpadDecimal,
  ],
  [NormalKeyCodeNames.Slash]: [
    NormalKeyCodes.Slash,
    NormalKeyCodes.NumpadDivide,
  ],
  [NormalKeyCodeNames.Semicolon]: [NormalKeyCodes.Semicolon],
  [NormalKeyCodeNames.Quote]: [NormalKeyCodes.Quote],
  [NormalKeyCodeNames.BracketLeft]: [NormalKeyCodes.BracketLeft],
  [NormalKeyCodeNames.BracketRight]: [NormalKeyCodes.BracketRight],
  [NormalKeyCodeNames.Backslash]: [NormalKeyCodes.Backslash],
  [NormalKeyCodeNames.Backquote]: [NormalKeyCodes.Backquote],
  // others
  [NormalKeyCodeNames.Space]: [NormalKeyCodes.Space],
  [NormalKeyCodeNames.Delete]: [NormalKeyCodes.Delete],
  [NormalKeyCodeNames.Tab]: [NormalKeyCodes.Tab],
  [NormalKeyCodeNames.CapsLock]: [NormalKeyCodes.CapsLock],
  [NormalKeyCodeNames.Enter]: [
    NormalKeyCodes.Enter,
    NormalKeyCodes.NumpadEnter,
  ],
  [NormalKeyCodeNames.Esc]: [NormalKeyCodes.Escape],
  [NormalKeyCodeNames.Escape]: [NormalKeyCodes.Escape],
  [NormalKeyCodeNames.Backspace]: [NormalKeyCodes.Backspace],
  [NormalKeyCodeNames.ArrowUp]: [NormalKeyCodes.ArrowUp],
  [NormalKeyCodeNames.ArrowDown]: [NormalKeyCodes.ArrowDown],
  [NormalKeyCodeNames.ArrowLeft]: [NormalKeyCodes.ArrowLeft],
  [NormalKeyCodeNames.ArrowRight]: [NormalKeyCodes.ArrowRight],
  [NormalKeyCodeNames.Home]: [NormalKeyCodes.Home],
  [NormalKeyCodeNames.End]: [NormalKeyCodes.End],
  [NormalKeyCodeNames.PageUp]: [NormalKeyCodes.PageUp],
  [NormalKeyCodeNames.PageDown]: [NormalKeyCodes.PageDown],
  [NormalKeyCodeNames.Insert]: [NormalKeyCodes.Insert],
};

export const keyCode2KeyCodeName: Record<KeyCode, KeyCodeName> = {
  // modifiers
  [ModifierKeyCodes.ControlLeft]: ModifierKeyCodeNames.ControlLeft,
  [ModifierKeyCodes.ControlRight]: ModifierKeyCodeNames.ControlRight,
  [ModifierKeyCodes.ShiftLeft]: ModifierKeyCodeNames.ShiftLeft,
  [ModifierKeyCodes.ShiftRight]: ModifierKeyCodeNames.ShiftRight,
  [ModifierKeyCodes.AltLeft]: ModifierKeyCodeNames.AltLeft,
  [ModifierKeyCodes.AltRight]: ModifierKeyCodeNames.AltRight,
  [ModifierKeyCodes.MetaLeft]: ModifierKeyCodeNames.MetaLeft,
  [ModifierKeyCodes.MetaRight]: ModifierKeyCodeNames.MetaRight,
  [ModifierKeyCodes.OSLeft]: ModifierKeyCodeNames.MetaLeft,
  [ModifierKeyCodes.OSRight]: ModifierKeyCodeNames.MetaRight,
  // functions
  [NormalKeyCodes.F1]: NormalKeyCodeNames.F1,
  [NormalKeyCodes.F2]: NormalKeyCodeNames.F2,
  [NormalKeyCodes.F3]: NormalKeyCodeNames.F3,
  [NormalKeyCodes.F4]: NormalKeyCodeNames.F4,
  [NormalKeyCodes.F5]: NormalKeyCodeNames.F5,
  [NormalKeyCodes.F6]: NormalKeyCodeNames.F6,
  [NormalKeyCodes.F7]: NormalKeyCodeNames.F7,
  [NormalKeyCodes.F8]: NormalKeyCodeNames.F8,
  [NormalKeyCodes.F9]: NormalKeyCodeNames.F9,
  [NormalKeyCodes.F10]: NormalKeyCodeNames.F10,
  [NormalKeyCodes.F11]: NormalKeyCodeNames.F11,
  [NormalKeyCodes.F12]: NormalKeyCodeNames.F12,
  // numbers
  [NormalKeyCodes.Digit1]: NormalKeyCodeNames.One,
  [NormalKeyCodes.Digit2]: NormalKeyCodeNames.Two,
  [NormalKeyCodes.Digit3]: NormalKeyCodeNames.Three,
  [NormalKeyCodes.Digit4]: NormalKeyCodeNames.Four,
  [NormalKeyCodes.Digit5]: NormalKeyCodeNames.Five,
  [NormalKeyCodes.Digit6]: NormalKeyCodeNames.Six,
  [NormalKeyCodes.Digit7]: NormalKeyCodeNames.Seven,
  [NormalKeyCodes.Digit8]: NormalKeyCodeNames.Eight,
  [NormalKeyCodes.Digit9]: NormalKeyCodeNames.Nine,
  [NormalKeyCodes.Digit0]: NormalKeyCodeNames.Zero,
  [NormalKeyCodes.Minus]: NormalKeyCodeNames.Minus,
  [NormalKeyCodes.Equal]: NormalKeyCodeNames.Equal,
  // numpad
  [NormalKeyCodes.Numpad1]: NormalKeyCodeNames.NumpadOne,
  [NormalKeyCodes.Numpad2]: NormalKeyCodeNames.NumpadTwo,
  [NormalKeyCodes.Numpad3]: NormalKeyCodeNames.NumpadThree,
  [NormalKeyCodes.Numpad4]: NormalKeyCodeNames.NumpadFour,
  [NormalKeyCodes.Numpad5]: NormalKeyCodeNames.NumpadFive,
  [NormalKeyCodes.Numpad6]: NormalKeyCodeNames.NumpadSix,
  [NormalKeyCodes.Numpad7]: NormalKeyCodeNames.NumpadSeven,
  [NormalKeyCodes.Numpad8]: NormalKeyCodeNames.NumpadEight,
  [NormalKeyCodes.Numpad9]: NormalKeyCodeNames.NumpadNine,
  [NormalKeyCodes.Numpad0]: NormalKeyCodeNames.NumpadZero,
  [NormalKeyCodes.NumLock]: NormalKeyCodeNames.NumLock,
  [NormalKeyCodes.NumpadEnter]: NormalKeyCodeNames.NumpadEnter,
  [NormalKeyCodes.NumpadDivide]: NormalKeyCodeNames.NumpadDivide,
  [NormalKeyCodes.NumpadMultiply]: NormalKeyCodeNames.NumpadMultiply,
  [NormalKeyCodes.NumpadSubtract]: NormalKeyCodeNames.NumpadSubtract,
  [NormalKeyCodes.NumpadAdd]: NormalKeyCodeNames.NumpadAdd,
  [NormalKeyCodes.NumpadDecimal]: NormalKeyCodeNames.NumpadDecimal,
  // words
  [NormalKeyCodes.KeyA]: NormalKeyCodeNames.A,
  [NormalKeyCodes.KeyB]: NormalKeyCodeNames.B,
  [NormalKeyCodes.KeyC]: NormalKeyCodeNames.C,
  [NormalKeyCodes.KeyD]: NormalKeyCodeNames.D,
  [NormalKeyCodes.KeyE]: NormalKeyCodeNames.E,
  [NormalKeyCodes.KeyF]: NormalKeyCodeNames.F,
  [NormalKeyCodes.KeyG]: NormalKeyCodeNames.G,
  [NormalKeyCodes.KeyH]: NormalKeyCodeNames.H,
  [NormalKeyCodes.KeyI]: NormalKeyCodeNames.I,
  [NormalKeyCodes.KeyJ]: NormalKeyCodeNames.J,
  [NormalKeyCodes.KeyK]: NormalKeyCodeNames.K,
  [NormalKeyCodes.KeyL]: NormalKeyCodeNames.L,
  [NormalKeyCodes.KeyM]: NormalKeyCodeNames.M,
  [NormalKeyCodes.KeyN]: NormalKeyCodeNames.N,
  [NormalKeyCodes.KeyO]: NormalKeyCodeNames.O,
  [NormalKeyCodes.KeyP]: NormalKeyCodeNames.P,
  [NormalKeyCodes.KeyQ]: NormalKeyCodeNames.Q,
  [NormalKeyCodes.KeyR]: NormalKeyCodeNames.R,
  [NormalKeyCodes.KeyS]: NormalKeyCodeNames.S,
  [NormalKeyCodes.KeyT]: NormalKeyCodeNames.T,
  [NormalKeyCodes.KeyU]: NormalKeyCodeNames.U,
  [NormalKeyCodes.KeyV]: NormalKeyCodeNames.V,
  [NormalKeyCodes.KeyW]: NormalKeyCodeNames.W,
  [NormalKeyCodes.KeyX]: NormalKeyCodeNames.X,
  [NormalKeyCodes.KeyY]: NormalKeyCodeNames.Y,
  [NormalKeyCodes.KeyZ]: NormalKeyCodeNames.Z,
  // punctuations
  [NormalKeyCodes.Comma]: NormalKeyCodeNames.Comma,
  [NormalKeyCodes.Period]: NormalKeyCodeNames.Period,
  [NormalKeyCodes.Slash]: NormalKeyCodeNames.Slash,
  [NormalKeyCodes.Semicolon]: NormalKeyCodeNames.Semicolon,
  [NormalKeyCodes.Quote]: NormalKeyCodeNames.Quote,
  [NormalKeyCodes.BracketLeft]: NormalKeyCodeNames.BracketLeft,
  [NormalKeyCodes.BracketRight]: NormalKeyCodeNames.BracketRight,
  [NormalKeyCodes.Backslash]: NormalKeyCodeNames.Backslash,
  [NormalKeyCodes.Backquote]: NormalKeyCodeNames.Backquote,
  // others
  [NormalKeyCodes.Space]: NormalKeyCodeNames.Space,
  [NormalKeyCodes.Escape]: NormalKeyCodeNames.Escape,
  [NormalKeyCodes.Backspace]: NormalKeyCodeNames.Backspace,
  [NormalKeyCodes.Delete]: NormalKeyCodeNames.Delete,
  [NormalKeyCodes.Tab]: NormalKeyCodeNames.Tab,
  [NormalKeyCodes.CapsLock]: NormalKeyCodeNames.CapsLock,
  [NormalKeyCodes.Enter]: NormalKeyCodeNames.Enter,
  [NormalKeyCodes.ArrowUp]: NormalKeyCodeNames.ArrowUp,
  [NormalKeyCodes.ArrowDown]: NormalKeyCodeNames.ArrowDown,
  [NormalKeyCodes.ArrowLeft]: NormalKeyCodeNames.ArrowLeft,
  [NormalKeyCodes.ArrowRight]: NormalKeyCodeNames.ArrowRight,
  [NormalKeyCodes.Home]: NormalKeyCodeNames.Home,
  [NormalKeyCodes.End]: NormalKeyCodeNames.End,
  [NormalKeyCodes.PageUp]: NormalKeyCodeNames.PageUp,
  [NormalKeyCodes.PageDown]: NormalKeyCodeNames.PageDown,
  [NormalKeyCodes.Insert]: NormalKeyCodeNames.Insert,
};

export const keyCodeName2LooseModeKeyCodeName: {
  [key in KeyCodeName]?: KeyCodeName;
} = {
  [ModifierKeyCodeNames.CtrlLeft]: ModifierKeyCodeNames.Ctrl,
  [ModifierKeyCodeNames.CtrlRight]: ModifierKeyCodeNames.Ctrl,
  [ModifierKeyCodeNames.Control]: ModifierKeyCodeNames.Ctrl,
  [ModifierKeyCodeNames.ControlLeft]: ModifierKeyCodeNames.Ctrl,
  [ModifierKeyCodeNames.ControlRight]: ModifierKeyCodeNames.Ctrl,
  [ModifierKeyCodeNames.ShiftLeft]: ModifierKeyCodeNames.Shift,
  [ModifierKeyCodeNames.ShiftRight]: ModifierKeyCodeNames.Shift,
  [ModifierKeyCodeNames.OptionLeft]: ModifierKeyCodeNames.Option,
  [ModifierKeyCodeNames.OptionRight]: ModifierKeyCodeNames.Option,
  [ModifierKeyCodeNames.AltLeft]: ModifierKeyCodeNames.Alt,
  [ModifierKeyCodeNames.AltRight]: ModifierKeyCodeNames.Alt,
  [ModifierKeyCodeNames.CommandLeft]: ModifierKeyCodeNames.Command,
  [ModifierKeyCodeNames.CommandRight]: ModifierKeyCodeNames.Command,
  [ModifierKeyCodeNames.MetaLeft]: ModifierKeyCodeNames.Meta,
  [ModifierKeyCodeNames.MetaRight]: ModifierKeyCodeNames.Meta,
  [NormalKeyCodeNames.NumpadOne]: NormalKeyCodeNames.One,
  [NormalKeyCodeNames.NumpadTwo]: NormalKeyCodeNames.Two,
  [NormalKeyCodeNames.NumpadThree]: NormalKeyCodeNames.Three,
  [NormalKeyCodeNames.NumpadFour]: NormalKeyCodeNames.Four,
  [NormalKeyCodeNames.NumpadFive]: NormalKeyCodeNames.Five,
  [NormalKeyCodeNames.NumpadSix]: NormalKeyCodeNames.Six,
  [NormalKeyCodeNames.NumpadSeven]: NormalKeyCodeNames.Seven,
  [NormalKeyCodeNames.NumpadEight]: NormalKeyCodeNames.Eight,
  [NormalKeyCodeNames.NumpadNine]: NormalKeyCodeNames.Nine,
  [NormalKeyCodeNames.NumpadZero]: NormalKeyCodeNames.Zero,
  [NormalKeyCodeNames.NumpadEnter]: NormalKeyCodeNames.Enter,
  [NormalKeyCodeNames.NumpadDivide]: NormalKeyCodeNames.Slash,
  [NormalKeyCodeNames.NumpadMultiply]: NormalKeyCodeNames.Multiply,
  [NormalKeyCodeNames.NumpadSubtract]: NormalKeyCodeNames.Minus,
  [NormalKeyCodeNames.NumpadAdd]: NormalKeyCodeNames.Plus,
  [NormalKeyCodeNames.NumpadDecimal]: NormalKeyCodeNames.Period,
};

export const ModifierKeyCodeOrder: ModifierKeyCode[] = [
  ModifierKeyCodes.ControlLeft,
  ModifierKeyCodes.ControlRight,
  ModifierKeyCodes.MetaLeft,
  ModifierKeyCodes.MetaRight,
  ModifierKeyCodes.OSLeft,
  ModifierKeyCodes.OSRight,
  ModifierKeyCodes.ShiftLeft,
  ModifierKeyCodes.ShiftRight,
  ModifierKeyCodes.AltLeft,
  ModifierKeyCodes.AltRight,
];
