import { AcceleratorParser } from './accelerator-parser';

const parser = new AcceleratorParser();

describe('parseAccelerator', () => {
  it('parse success', () => {
    expect(parser.parseAccelerator('Ctrl+a')).toMatchInlineSnapshot(`
[
  [
    "ControlLeft",
    "ControlRight",
  ],
  [
    "a",
  ],
]
`);
    expect(parser.parseAccelerator('Control+a')).toMatchInlineSnapshot(`
[
  [
    "ControlLeft",
    "ControlRight",
  ],
  [
    "a",
  ],
]
`);
    expect(parser.parseAccelerator('ControlLeft+a')).toMatchInlineSnapshot(`
[
  [
    "ControlLeft",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('ControlRight+a')).toMatchInlineSnapshot(`
[
  [
    "ControlRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('ControlOrCommand+a'))
      .toMatchInlineSnapshot(`
[
  [
    "ControlLeft",
    "ControlRight",
    "MetaLeft",
    "MetaRight",
    "OSLeft",
    "OSRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('Shift+a')).toMatchInlineSnapshot(`
[
  [
    "ShiftLeft",
    "ShiftRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('ShiftLeft+a')).toMatchInlineSnapshot(`
[
  [
    "ShiftLeft",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('ShiftRight+a')).toMatchInlineSnapshot(`
[
  [
    "ShiftRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('Alt+a')).toMatchInlineSnapshot(`
[
  [
    "AltLeft",
    "AltRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('AltLeft+a')).toMatchInlineSnapshot(`
[
  [
    "AltLeft",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('AltRight+a')).toMatchInlineSnapshot(`
[
  [
    "AltRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('Option+a')).toMatchInlineSnapshot(`
[
  [
    "AltLeft",
    "AltRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('OptionLeft+a')).toMatchInlineSnapshot(`
[
  [
    "AltLeft",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('OptionRight+a')).toMatchInlineSnapshot(`
[
  [
    "AltRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('Meta+a')).toMatchInlineSnapshot(`
[
  [
    "MetaLeft",
    "MetaRight",
    "OSLeft",
    "OSRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('MetaLeft+a')).toMatchInlineSnapshot(`
[
  [
    "MetaLeft",
    "OSLeft",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('MetaRight+a')).toMatchInlineSnapshot(`
[
  [
    "MetaRight",
    "OSRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('Command+a')).toMatchInlineSnapshot(`
[
  [
    "MetaLeft",
    "MetaRight",
    "OSLeft",
    "OSRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('CommandLeft+a')).toMatchInlineSnapshot(`
[
  [
    "MetaLeft",
    "OSLeft",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('CommandRight+a')).toMatchInlineSnapshot(`
[
  [
    "MetaRight",
    "OSRight",
  ],
  [
    "KeyA",
  ],
]
`);

    expect(parser.parseAccelerator('Ctrl+i')).toMatchInlineSnapshot(`
[
  [
    "ControlLeft",
    "ControlRight",
  ],
  [
    "KeyI",
  ],
]
`);
    expect(parser.parseAccelerator('ControlLeft+Option+a'))
      .toMatchInlineSnapshot(`
[
  [
    "AltLeft+ControlLeft",
    "AltRight+ControlLeft",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('Command+Option+a')).toMatchInlineSnapshot(`
[
  [
    "AltLeft+MetaLeft",
    "AltLeft+MetaRight",
    "AltLeft+OSLeft",
    "AltLeft+OSRight",
    "AltRight+MetaLeft",
    "AltRight+MetaRight",
    "AltRight+OSLeft",
    "AltRight+OSRight",
  ],
  [
    "KeyA",
  ],
]
`);
    expect(parser.parseAccelerator('Command+Option+Shift+='))
      .toMatchInlineSnapshot(`
[
  [
    "AltLeft+MetaLeft+ShiftLeft",
    "AltLeft+MetaRight+ShiftLeft",
    "AltLeft+OSLeft+ShiftLeft",
    "AltLeft+OSRight+ShiftLeft",
    "AltRight+MetaLeft+ShiftLeft",
    "AltRight+MetaRight+ShiftLeft",
    "AltRight+OSLeft+ShiftLeft",
    "AltRight+OSRight+ShiftLeft",
    "AltLeft+MetaLeft+ShiftRight",
    "AltLeft+MetaRight+ShiftRight",
    "AltLeft+OSLeft+ShiftRight",
    "AltLeft+OSRight+ShiftRight",
    "AltRight+MetaLeft+ShiftRight",
    "AltRight+MetaRight+ShiftRight",
    "AltRight+OSLeft+ShiftRight",
    "AltRight+OSRight+ShiftRight",
  ],
  [
    "Equal",
  ],
]
`);
    expect(parser.parseAccelerator('ControlOrCommand+Option+Shift+i'))
      .toMatchInlineSnapshot(`
[
  [
    "AltLeft+ControlLeft+ShiftLeft",
    "AltLeft+ControlRight+ShiftLeft",
    "AltLeft+MetaLeft+ShiftLeft",
    "AltLeft+MetaRight+ShiftLeft",
    "AltLeft+OSLeft+ShiftLeft",
    "AltLeft+OSRight+ShiftLeft",
    "AltRight+ControlLeft+ShiftLeft",
    "AltRight+ControlRight+ShiftLeft",
    "AltRight+MetaLeft+ShiftLeft",
    "AltRight+MetaRight+ShiftLeft",
    "AltRight+OSLeft+ShiftLeft",
    "AltRight+OSRight+ShiftLeft",
    "AltLeft+ControlLeft+ShiftRight",
    "AltLeft+ControlRight+ShiftRight",
    "AltLeft+MetaLeft+ShiftRight",
    "AltLeft+MetaRight+ShiftRight",
    "AltLeft+OSLeft+ShiftRight",
    "AltLeft+OSRight+ShiftRight",
    "AltRight+ControlLeft+ShiftRight",
    "AltRight+ControlRight+ShiftRight",
    "AltRight+MetaLeft+ShiftRight",
    "AltRight+MetaRight+ShiftRight",
    "AltRight+OSLeft+ShiftRight",
    "AltRight+OSRight+ShiftRight",
  ],
  [
    "KeyI",
  ],
]
`);
  });

  it('parse error', () => {
    expect(() =>
      parser.parseAccelerator('Control+Shift+1+2+3+4+5+6'),
    ).toThrowErrorMatchingInlineSnapshot(
      '"parse accelerator failed in position 16."',
    );
    expect(() =>
      parser.parseAccelerator('Control+i+i'),
    ).toThrowErrorMatchingInlineSnapshot(
      '"parse accelerator failed in position 10."',
    );
    expect(() =>
      parser.parseAccelerator('ctrl+i'),
    ).toThrowErrorMatchingInlineSnapshot(
      '"parse accelerator failed in position 0."',
    );
    expect(() =>
      parser.parseAccelerator('Control+i+Option'),
    ).toThrowErrorMatchingInlineSnapshot(
      '"parse accelerator failed in position 11."',
    );
    expect(() =>
      parser.parseAccelerator('Control+'),
    ).toThrowErrorMatchingInlineSnapshot(
      '"parse accelerator failed in position 8."',
    );
  });

  it('shortcut alias', () => {
    expect(parser.parseAccelerator('Meta+Option')).toEqual(
      parser.parseAccelerator('Command+Alt'),
    );
  });
});
